<?php

    $NAVBAR="";
    
    $NAVBAR.="<div style=\"background-color:#101010\">\n";
    $NAVBAR.="<nav class=\"navbar navbar-inverse navbar-fixed-top\">\n";
    $NAVBAR.="<div class=\"container-fluid\">\n";
    $NAVBAR.="<!-- Brand and toggle get grouped for better mobile display -->\n";
    $NAVBAR.="<div class=\"navbar-header\">\n";
    $NAVBAR.="<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbarmenu\" aria-expanded=\"false\">\n";
    $NAVBAR.="<span class=\"sr-only\">Toggle navigation</span>\n";
    $NAVBAR.="<span class=\"icon-bar\"></span>\n";
    $NAVBAR.="<span class=\"icon-bar\"></span>\n";
    $NAVBAR.="<span class=\"icon-bar\"></span>\n";
    $NAVBAR.="</button>\n";
    $NAVBAR.="<!-- brand -->\n";
    $NAVBAR.="<a class=\"navbar-brand\" href=\"/\">aireem</a>\n";
    $NAVBAR.="</div>\n\n";
    $NAVBAR.="<!-- Collect the nav links, forms, and other content for toggling -->\n";
    $NAVBAR.="<div class=\"collapse navbar-collapse\" id=\"navbarmenu\">\n";
    $NAVBAR.="<!-- quick links -->\n";
    $NAVBAR.="<ul class=\"nav navbar-nav\">\n";
    $NAVBAR.="<li>\n";
    $NAVBAR.="<a href=\"/\">Prenota</a>\n";
    $NAVBAR.="</li>\n";
    $NAVBAR.="<li>\n";
    $NAVBAR.="<a href=\"offer.php\">Offri</a>\n";
    $NAVBAR.="</li>\n";
    $NAVBAR.="</ul>\n";
    $NAVBAR.="<!-- main elements -->\n";
    $NAVBAR.="<ul class=\"nav navbar-nav navbar-right\">\n";
    $NAVBAR.="<!-- notifications -->\n";
    $NAVBAR.="<li class=\"dropdown\">\n";
    $NAVBAR.="<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
    $NAVBAR.="<span class=\"glyphicon glyphicon-bell glyphicon-lg\"></span>\n";
    $NAVBAR.="</a>\n";
    $NAVBAR.="<ul class=\"dropdown-menu\">\n";
    $NAVBAR.="<li><a href=\"#\">Notifica 1</a></li>\n";
    $NAVBAR.="<li><a href=\"#\">Notifica 2</a></li>\n";
    $NAVBAR.="<li><a href=\"#\">Notifica 3</a></li>\n";
    $NAVBAR.="<li><a href=\"#\">Notifica 4</a></li>\n";
    $NAVBAR.="<li role=\"separator\" class=\"divider\"></li>\n";
    $NAVBAR.="<li><a href=\"#\">Vedi tutte le notifiche</a></li>\n";
    $NAVBAR.="</ul>\n";
    $NAVBAR.="</li>\n";
    $NAVBAR.="<!-- messages -->\n";
    $NAVBAR.="<li class=\"dropdown\">";
    $NAVBAR.="<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
    $NAVBAR.="<span class=\"glyphicon glyphicon-comment glyphicon-lg\"></span>\n";
    $NAVBAR.="</a>\n";
    $NAVBAR.="<ul class=\"dropdown-menu\">\n";
    $NAVBAR.="<li><a href=\"#\">Messaggio 1</a></li>\n";
    $NAVBAR.="<li><a href=\"#\">Messaggio 2</a></li>\n";
    $NAVBAR.="<li><a href=\"#\">Messaggio 3</a></li>\n";
    $NAVBAR.="<li><a href=\"#\">Messaggio 4</a></li>\n";
    $NAVBAR.="<li role=\"separator\" class=\"divider\"></li>\n";
    $NAVBAR.="<li><a href=\"#\">Vedi tutti i messaggi privati</a></li>\n";
    $NAVBAR.="</ul>\n";
    $NAVBAR.="</li>\n";
    $NAVBAR.="<!-- profile -->\n";
    $NAVBAR.="<li class=\"dropdown\">\n";
    $NAVBAR.="<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
    $NAVBAR.="<img src=\"".$_SESSION["usrProPic"]."\" class=\"img-circle\" alt=\"Me\" width=\"20\" height=\"20\">\n";
    $NAVBAR.="</a>\n";
    $NAVBAR.="<ul class=\"dropdown-menu\">\n";
    $NAVBAR.="<li><a href=\"myservices.php\">Servizi offerti</a></li>\n";
    $NAVBAR.="<li><a href=\"user.php?id=".$_SESSION["usrID"]."\">Profilo</a></li>\n";
    $NAVBAR.="<li role=\"separator\" class=\"divider\"></li>\n";
    $NAVBAR.="<li><a href=\"logout.php\">Esci</a></li>\n";
    $NAVBAR.="</ul>\n";
    $NAVBAR.="</li>\n";
    $NAVBAR.="</ul>\n";
    $NAVBAR.="</div><!-- /.navbar-collapse -->\n";
    $NAVBAR.="</div><!-- /.container-fluid -->\n";
    $NAVBAR.="</nav>\n";
    $NAVBAR.="</div><!-- /.navbar -->\n";
    $NAVBAR.="</div><!-- /.container-fluid -->\n";
    $NAVBAR.="</nav>\n";
    $NAVBAR.="</div><!-- /.navbar -->\n";

?>